CREATE TABLE users (
   id CHAR(36) PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255) UNIQUE NOT NULL,
   password VARCHAR(255) NOT NULL,
   cpf BIGINT UNSIGNED UNIQUE,
   description VARCHAR(255),
   phone_number BIGINT UNSIGNED UNIQUE,
   is_admin BOOLEAN DEFAULT false,
   created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
   INDEX (id)
);