version: "3.3"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: "CAMPI"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3003:3306"
    volumes:
      - campi-db:/var/lib/mysql

volumes:
  campi-db:
