version: "3.3"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: "CAMPI"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3002:3306"
    volumes:
      - campi-db:/var/lib/mysql
  api-campi:
    build: $PWD/api
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    volumes:
      - $PWD/api:/api

volumes:
  campi-db:
